-- MySQL Script generated by MySQL Workbench
-- Tue May 26 21:15:52 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`stroj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`stroj` (
  `VIN` VARCHAR(45) NOT NULL,
  `Popis` TINYTEXT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `DatumPridani` DATETIME NOT NULL,
  PRIMARY KEY (`VIN`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`IoTPrvek`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`IoTPrvek` (
  `SerioveCislo` VARCHAR(45) NOT NULL,
  `Nazev` VARCHAR(45) NOT NULL,
  `Popis` TINYTEXT NULL,
  `DatumPridani` DATETIME NULL,
  PRIMARY KEY (`SerioveCislo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`udajeStroj`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`udajeStroj` (
  `GPS` VARCHAR(45) NOT NULL,
  `Stav` INT NOT NULL,
  `StavBaterie` TINYINT NOT NULL,
  `X` DECIMAL(10,9) NOT NULL,
  `Y` DECIMAL(10,9) NOT NULL,
  `Z` DECIMAL(10,9) NOT NULL,
  `Datum` DATETIME NOT NULL,
  `stroj_VIN` VARCHAR(45) NOT NULL,
  `IoTPrvek_SerioveCislo` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`Datum`, `stroj_VIN`, `IoTPrvek_SerioveCislo`),
  INDEX `fk_udajeStroj_stroj_idx` (`stroj_VIN` ASC) VISIBLE,
  INDEX `fk_udajeStroj_IoTPrvek1_idx` (`IoTPrvek_SerioveCislo` ASC) VISIBLE,
  CONSTRAINT `fk_udajeStroj_stroj`
    FOREIGN KEY (`stroj_VIN`)
    REFERENCES `mydb`.`stroj` (`VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_udajeStroj_IoTPrvek1`
    FOREIGN KEY (`IoTPrvek_SerioveCislo`)
    REFERENCES `mydb`.`IoTPrvek` (`SerioveCislo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`udajeTenzometr`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`udajeTenzometr` (
  `oznaceniTenzo` VARCHAR(45) NOT NULL,
  `hodnota` DECIMAL(3,2) NOT NULL,
  `udajeStroj_Datum` DATETIME NOT NULL,
  `udajeStroj_stroj_VIN` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`oznaceniTenzo`, `udajeStroj_stroj_VIN`, `udajeStroj_Datum`),
  INDEX `fk_tenzometr_udajeStroj1_idx` (`udajeStroj_Datum` ASC, `udajeStroj_stroj_VIN` ASC) VISIBLE,
  CONSTRAINT `fk_tenzometr_udajeStroj1`
    FOREIGN KEY (`udajeStroj_Datum` , `udajeStroj_stroj_VIN`)
    REFERENCES `mydb`.`udajeStroj` (`Datum` , `stroj_VIN`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
